#include "py/obj.h"

extern const mp_obj_type_t PicosystemBuffer_type;
extern const mp_obj_type_t PicosystemVoice_type;

MP_DECLARE_CONST_FUN_OBJ_0(picosystem_init_obj);
MP_DECLARE_CONST_FUN_OBJ_0(picosystem_reset_obj);
MP_DECLARE_CONST_FUN_OBJ_0(picosystem_tick_obj);

// voice.cpp

MP_DECLARE_CONST_FUN_OBJ_KW(picosystem_play_obj);

// state.cpp

MP_DECLARE_CONST_FUN_OBJ_VAR_BETWEEN(picosystem_pen_obj);
MP_DECLARE_CONST_FUN_OBJ_VAR_BETWEEN(picosystem_clip_obj);
MP_DECLARE_CONST_FUN_OBJ_1(picosystem_blend_obj);
MP_DECLARE_CONST_FUN_OBJ_VAR_BETWEEN(picosystem_target_obj);
MP_DECLARE_CONST_FUN_OBJ_2(picosystem_camera_obj);
MP_DECLARE_CONST_FUN_OBJ_1(picosystem_spritesheet_obj);

// primitives.cpp

MP_DECLARE_CONST_FUN_OBJ_2(picosystem_pixel_obj);
MP_DECLARE_CONST_FUN_OBJ_3(picosystem_hline_obj);
MP_DECLARE_CONST_FUN_OBJ_3(picosystem_vline_obj);

MP_DECLARE_CONST_FUN_OBJ_0(picosystem_clear_obj);

MP_DECLARE_CONST_FUN_OBJ_VAR_BETWEEN(picosystem_rect_obj);
MP_DECLARE_CONST_FUN_OBJ_VAR_BETWEEN(picosystem_frect_obj);

MP_DECLARE_CONST_FUN_OBJ_3(picosystem_circle_obj);
MP_DECLARE_CONST_FUN_OBJ_3(picosystem_fcircle_obj);

MP_DECLARE_CONST_FUN_OBJ_VAR_BETWEEN(picosystem_ellipse_obj);
MP_DECLARE_CONST_FUN_OBJ_VAR_BETWEEN(picosystem_fellipse_obj);

MP_DECLARE_CONST_FUN_OBJ_VAR(picosystem_poly_obj);
MP_DECLARE_CONST_FUN_OBJ_VAR(picosystem_fpoly_obj);

MP_DECLARE_CONST_FUN_OBJ_VAR_BETWEEN(picosystem_line_obj);
MP_DECLARE_CONST_FUN_OBJ_VAR_BETWEEN(picosystem_blit_obj);
MP_DECLARE_CONST_FUN_OBJ_VAR_BETWEEN(picosystem_sprite_obj);
MP_DECLARE_CONST_FUN_OBJ_VAR_BETWEEN(picosystem_text_obj);
MP_DECLARE_CONST_FUN_OBJ_1(picosystem_text_width_obj);

// utility.cpp

MP_DECLARE_CONST_FUN_OBJ_VAR_BETWEEN(picosystem_rgb_obj);
MP_DECLARE_CONST_FUN_OBJ_VAR_BETWEEN(picosystem_hsv_obj);

MP_DECLARE_CONST_FUN_OBJ_VAR_BETWEEN(picosystem_intersects_obj);
MP_DECLARE_CONST_FUN_OBJ_VAR_BETWEEN(picosystem_intersection_obj);
MP_DECLARE_CONST_FUN_OBJ_VAR_BETWEEN(picosystem_contains_obj);

// hardware.cpp

MP_DECLARE_CONST_FUN_OBJ_1(picosystem_pressed_obj);
MP_DECLARE_CONST_FUN_OBJ_1(picosystem_button_obj);
MP_DECLARE_CONST_FUN_OBJ_0(picosystem_battery_obj);
MP_DECLARE_CONST_FUN_OBJ_3(picosystem_led_obj);
MP_DECLARE_CONST_FUN_OBJ_1(picosystem_backlight_obj);